import { Event } from '@/types';

export const mockEvents: Event[] = [
  {
    id: '1',
    title: 'React Summit 2024',
    description: 'Join us for the biggest React conference of the year. Learn about the latest features, best practices, and network with fellow developers.',
    date: new Date('2024-03-15T09:00:00'),
    capacity: 500,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
    organizer: {
      id: 'org1',
      username: 'reactteam',
      email: 'team@react.com',
      password: '',
      roles: ['organizer'],
      events: [],
      attendedEvents: [],
    },
    attendees: [],
  },
  {
    id: '2',
    title: 'TypeScript Workshop',
    description: 'Deep dive into TypeScript advanced patterns and features. Perfect for developers looking to level up their TypeScript skills.',
    date: new Date('2024-03-20T14:00:00'),
    capacity: 100,
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-01-05'),
    organizer: {
      id: 'org2',
      username: 'tsteam',
      email: 'team@typescript.com',
      password: '',
      roles: ['organizer'],
      events: [],
      attendedEvents: [],
    },
    attendees: [],
  },
  {
    id: '3',
    title: 'Web3 & Blockchain Meetup',
    description: 'Explore the world of decentralized applications and blockchain technology. Network with crypto enthusiasts and developers.',
    date: new Date('2024-04-01T18:00:00'),
    capacity: 200,
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-10'),
    organizer: {
      id: 'org3',
      username: 'web3community',
      email: 'hello@web3.com',
      password: '',
      roles: ['organizer'],
      events: [],
      attendedEvents: [],
    },
    attendees: [],
  },
  {
    id: '4',
    title: 'AI & Machine Learning Conference',
    description: 'Discover the latest trends in AI and ML. Hear from industry leaders and researchers about cutting-edge developments.',
    date: new Date('2024-04-10T10:00:00'),
    capacity: 300,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
    organizer: {
      id: 'org4',
      username: 'aiconf',
      email: 'info@aiconf.com',
      password: '',
      roles: ['organizer'],
      events: [],
      attendedEvents: [],
    },
    attendees: [],
  },
  {
    id: '5',
    title: 'DevOps Best Practices',
    description: 'Learn about modern DevOps practices, CI/CD pipelines, and infrastructure as code. Hands-on workshops included.',
    date: new Date('2024-04-15T09:00:00'),
    capacity: 150,
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-01-20'),
    organizer: {
      id: 'org5',
      username: 'devopsorg',
      email: 'contact@devops.com',
      password: '',
      roles: ['organizer'],
      events: [],
      attendedEvents: [],
    },
    attendees: [],
  },
  {
    id: '6',
    title: 'Mobile Dev Day',
    description: 'All things mobile development - iOS, Android, React Native, and Flutter. Connect with mobile developers worldwide.',
    date: new Date('2024-04-25T11:00:00'),
    capacity: 250,
    createdAt: new Date('2024-01-25'),
    updatedAt: new Date('2024-01-25'),
    organizer: {
      id: 'org6',
      username: 'mobiledevs',
      email: 'team@mobiledev.com',
      password: '',
      roles: ['organizer'],
      events: [],
      attendedEvents: [],
    },
    attendees: [],
  },
];
